### ISSUE TITLE
l don't know that why the linear twist always grow up!!!!

### ISSUE THREAD

**Issue by woshinidiesb** [fetty31/fast_LIMO#1]
l give the code my data and l found the linear twist grow up all the time .then l look the odometry data that show me the linear twist x is zero !!! l don't know why ,if you tell me the reason ,l'll appreciate you !!!!
![截图 2024-08-13 23-40-03](https://github.com/user-attachments/assets/e64cfbc1-abfb-4dcf-a075-d01c3a50428d)

**Comment by woshinidiesb** [comment]
l found the reason that why the twist always grow up,i think it may be caused the frequency imu and error frame id ,now l want to know that what you suggest us to use whice a kind of imu

**Comment by fetty31** [comment]
Hi,

I'm afraid I won't be able to help with this very little information. Could you give some more context about the rosbag you're playing (e.g. sensor rates, sensor types, does it start at stand still, max. linear accel. and rotational velocity, etc.)?

What I have understood by now is that the output linear velocity is diverging (always growing up), does the position also diverge? It would be better if you launch Fast LIMO with the _rviz:=True_ flag so you can check if the algorithm is able to initialize as expected. The initialization is the most sensible part, as it starts to match between consecutive LiDAR frames, if it fails you should check the LiDAR and IMU extrinsics in _config/params.yaml_. Finally, take in mind that Fast LIMO will be broadcasting a TF between _world_ and _body_ frames (specified in _config/params.yaml_), make sure that there's no such transform being published by the rosbag itself.

As for the kind of IMU that you mention, it depends on the motion rate of your robot. For a low speed robot, the minimum publish rate I recommend is 80Hz.

**Comment by fetty31** [comment]
After checking the current ros2-humble implementation I've found some critical errors that were probably causing the algorithm's divergence. I have fixed the errors and checked that the current commit works with some bag files. 

Please pull this last modification and try again. I now consider this issue as closed. Thank you for your input!

**Comment by woshinidiesb** [comment]
First at all,thank you very much for your reply.l found a few method  about how to&nbsp; combine gnss to fast_lio at last week.lt's named that  FAST_LIO_SAM(https://github.com/kahowang/FAST_LIO_SAM)  and FAST-LIO-Multi-Sensor-Fusion(https://github.com/zhh2005757/FAST-LIO-Multi-Sensor-Fusion)  .the fast_lio_samcombine gnss to fast_lio in gtsam .however, the  FAST-LIO-Multi-Sensor-Fusion that even use the odometry to constraint  pose combine gnss to fast_lio in ieskf , but the both code is in  ros1,however,l can't transform it to ros2 and use it.May be the both  code can give you some idea



★往事“曾经
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fetty31/fast_LIMO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月15日(星期四) 凌晨1:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fetty31/fast_LIMO] l don't know that why the linear twist always grow up!!!! (Issue #1)





 
After checking the current ros2-humble implementation I've found some critical errors that were probably causing the algorithm's divergence. I have fixed the errors and checked that the current commit works with some bag files.
 
Please pull this last modification and try again. I now consider this issue as closed. Thank you for your input!

**Comment by woshinidiesb** [comment]
Hello, the new problem on the hub's issues top makes me very miserable, I don't know what is wrong, do you have time to help me take a look recently，please！
