### ISSUE TITLE
how to improve the fast_limo performance

### ISSUE THREAD

**Issue by woshinidiesb** [fetty31/fast_LIMO#2]
Hi,first at all,Thank you so much for sharing,l learn a lot knowledge from the code. last week ,l feel confuse about that linear twist grow up all the time .thank you give me answer and l found my mistake .
In outdoor environments, I found some discrepancies when comparing the trajectory of lio with that of gps. Therefore, I want to use gps to constrain fast_limo in outdoor environments, but I don't know how to improve it. I hope you can give some suggestions.

**Comment by woshinidiesb** [comment]
![截图 2024-08-20 09-07-12](https://github.com/user-attachments/assets/eaf33d87-2374-47d9-9c4f-31415adc3c36)

**Comment by woshinidiesb** [comment]
As shown in the figure above, the white line represents the GPS RTK trajectory, while the red line represents the odometer trajectory. The maximum error is approximately 3 meters.

**Comment by fetty31** [comment]
Hi,

As specified in the Future Work section, is possible that at some point I add a backend solution for GPS landmarks. 

For now, keep in mind that Fast-LIMO has been developed with the purpose to be used with a modified LiDAR driver, sending the scan packets as they're read, instead of waiting for a full LiDAR rotation. Actually, the multi-threaded implementation takes advantage of this setup. For low speed movements, a 10Hz LiDAR input and 80Hz-500Hz IMU inputs are enough for keeping the error small, but for aggressive movements (specially fast rotations) you should try with a modified LiDAR driver, sending the scan packets at a higher rate (20Hz-100Hz). You can check [this velodyne driver fork](https://github.com/fetty31/velodyne) if you want some example of a modified LiDAR driver.

**Comment by fetty31** [comment]
Hello again @woshinidiesb,

FYI now there's a loop closure branch with pose graph optimization for long-term odometry drift correction of Fast-LIMO. For now it's only updated to ROS Noetic. However, Fast-LIMO is implemented as a stand-alone library so the only part that actually changes from ROS1 to ROS2 is the wrapper inside the src/ folder. I hope this is useful for your use-case.

**Comment by woshinidiesb** [comment]
Hi,first at all,Thank you so much for sharing,l'll try to finish the ROS2 wrapper ,If I encounter any issues, I will raise them in this issue or send you an email.

**Comment by woshinidiesb** [comment]
> 你好再次@woshinidiesb，
> 
> FYI现在有一个循环闭合分支与姿势图优化的长期里程漂移校正的快速LIMO。目前只更新到ROS Noetic。然而，Fast-LIMO是作为一个独立的库实现的，所以从ROS 1到ROS 2的唯一变化是src/文件夹中的包装器。我希望这对你的用例有用。

Just now I tried to run the loop branch with docker, and found that docker was not successfully encapsulated, and there was an error that the pcl library was not found, can you adjust docker

**Comment by fetty31** [comment]
Hi, the Dockerfile and the scripts were not updated with the extra dependencies for the loop closure branch. Now it should be all okey.

**Comment by woshinidiesb** [comment]
Hello, first of all, thank you for your fast_limo package, which has  helped me understand laser radar rangefinders a bit better. Recently, I  have encountered a problem when using it and don't know how to solve it.  I hope you can give me some advice. Because of the memory limit on the  experimental vehicle, I have to limit the memory usage of the  rangefinder. When I set localmap to true, the rangefinder starts to  drift severely and even stops working. I have used your rosbag and  cat.param files to verify this function, but the problem still exists.  Is this function incomplete? If not, could you provide any ideas? By the  way, I am using the ros2 humble branch.


&nbsp;


★往事“曾经
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Oriol ***@***.***&gt;; 
发送时间: 2024年11月22日(星期五) 凌晨1:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fetty31/fast_LIMO] how to improve the fast_limo performance (Issue #2)














 
Closed #2 as completed.
